export const SEARCH_POKEMON = "SEARCH_POKEMON";
export const QUERY_REJECTED = "QUERY_REJECTED";
export const QUERY_RESOLVED = "QUERY_RESOLVED";
export const QUERY_TODOS_LIST = "QUERY_TODOS_LIST";
export const TODO_QUERY_REJECTED = "TODO_QUERY_REJECTED";
export const TODO_QUERY_RESOLVED = "TODO_QUERY_RESOLVED";
export const QUERY_SINGLE_TODO = "QUERY_SINGLE_TODO";

