export const SEARCH_POKEMON = "SEARCH_POKEMON";
export const QUERY_REJECTED = "QUERY_REJECTED";
export const QUERY_RESOLVED = "QUERY_RESOLVED";
export const QUERY_TODOS_LIST = "QUERY_TODOS_LIST";
export const TODO_QUERY_REJECTED = "TODO_QUERY_REJECTED";
export const TODO_QUERY_RESOLVED = "TODO_QUERY_RESOLVED";
export const PROMISE_RESOLVED = "PROMISE_RESOLVED";
export const PROMISE_REJECTED = "PROMISE_REJECTED";
export const PROMISE_PENDING = "PROMISE_PENDING";
export const QUERY_SINGLE_TODO = "QUERY_SINGLE_TODO";
export const NAME_SEARCH = "NAME_SEARCH";
export const NAME_RESOLVED = "NAME_RESOLVED";
export const NAME_REJECTED = "NAME_REJECTED";

